
if(CMAKE_ARGC LESS_EQUAL 3)
    message("Usage : cmake -P git-cmd.cmake <git cmd>")
    message("   The given git cmd will be applied to all directories in the current directory")
else()
    find_package(Git REQUIRED)
    math(EXPR argEnd "${CMAKE_ARGC} - 1")
    foreach(i RANGE 3 ${argEnd})
        list(APPEND gitCmd "${CMAKE_ARGV${i}}")
    endforeach()
    file(GLOB dynamicStaticDirectories RELATIVE ${CMAKE_CURRENT_LIST_DIR} *)
    foreach(dynamicStaticDirectory ${dynamicStaticDirectories})
        if(IS_DIRECTORY "${dynamicStaticDirectory}")
            message("================================================================================")
            message("Processing git cmd [${gitCmd}] for ${dynamicStaticDirectory}/")
            execute_process(COMMAND ${GIT_EXECUTABLE} -C "${dynamicStaticDirectory}" ${gitCmd})
        endif()
    endforeach()
endif()
